name: ci for cli

on:
  push:
    paths:
      - "gogo-cli/**"
      - ".github/workflows/ci_cli.yml"

jobs:
  build-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    env:
      VERSION: 0.0.1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: Go build
        working-directory: ./gogo-cli
        run: |
          bash -x ./release.sh ${{ env.VERSION }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli
          path: ./gogo-cli/release_${{ env.VERSION }}
          retention-days: 7