name: ci for server and web

on:
  push:
    paths:
      - "gogo-server/**"
      - "gogo-web/**"
      - ".github/workflows/ci_server_and_web.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - build_name: linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
      runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}
    - name: Cargo build
      run: cargo build --release ${{ matrix.target && '--target' }} ${{ matrix.target }}
      env:
        RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
        MACOSX_DEPLOYMENT_TARGET: ${{ matrix.MACOSX_DEPLOYMENT_TARGET }}
    